spring:
  cloud:
    gateway:
      routes:
        - id: index12306-user-service
          uri: lb://index12306-user-service/api/user-service/**
          predicates:
            - Path=/api/user-service/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/user-service/passenger
                  - /api/user-service/query
                  - /api/user-service/logout

        - id: index12306-ticket-service
          uri: lb://index12306-ticket-service/api/ticket-service/**
          predicates:
            - Path=/api/ticket-service/**

        - id: index12306-pay-service
          uri: lb://index12306-pay-service/api/pay-service/**
          predicates:
            - Path=/api/pay-service/**
